### ISSUE TITLE
Use case description

### ISSUE THREAD

**Issue by lolmaus** [dfreeman/ember-cli-deploy-git-ci#1]
This addon is doing something awesome, but I don't understand what exactly.

Can you please update the readme with a use case describing how this addon is useful?

**Comment by dfreeman** [comment]
My assumption going into this was that this addon is useful for exactly the set of people who already understand why they need it, which may have been totally off-base 🙂 

If I can ask, what brought you here in the first place? Updating the README will be easier if I can understand how people are finding this without knowing they're looking for it.

**Comment by lolmaus** [comment]
Your addon has been mentioned in the Ember Weekly newsletter.

I have some experience with `ember-cli-deploy`, including writing a custom plugin, so I got interested with your efforts. I'm curious what can be achieved with this addon.

**Comment by dfreeman** [comment]
Ah! I didn't realize this had actually been picked up somewhere. I've fleshed out the README a little to hopefully be more explicit about what this is for :)

**Comment by lolmaus** [comment]
Ah, so it lets you deploy from the CI. :sweat_smile: That's all I needed to hear. :trollface: 

Thank you for the readme update.

**Comment by dfreeman** [comment]
This was literally the first line in the README even before my update 😛

> This is an ember-cli-deploy plugin for managing deployments to a git branch in a CI environment like Travis.

**Comment by lolmaus** [comment]
"managing deployments" sounds fancy, I didn't realize it means triggering a deploy. :finnadie:
